version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dochojski/phishing-sms:local
    container_name: phishing-sms-app
    ports:
      - "8080:8080"
    environment:
      WEBRISK_BASE_URL: "http://webrisk-stub:8080"
      WEBRISK_API_TOKEN: "dummy"
      ALLOW_SCAN: "true"
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      - webrisk-stub
  webrisk-stub:
    image: wiremock/wiremock:3.6.0
    container_name: webrisk-stub
    ports:
      - "9090:8080"
    command: ["--disable-request-logging"]
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings:ro