name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B verify --file pom.xml

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=dochojski/phishing-sms
          VERSION=0.1.0
          GIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)

          docker build -t $IMAGE:latest -t $IMAGE:$VERSION -t $IMAGE:$GIT_SHA .

      - name: Push Docker image
        run: |
          IMAGE=dochojski/phishing-sms
          VERSION=0.1.0
          GIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)

          docker push $IMAGE:latest
          docker push $IMAGE:$VERSION
          docker push $IMAGE:$GIT_SHA
